#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join
#!/usr/bin/env ruby
puts ARGV[0].scan(/School/).join

